controller_manager:
  ros__parameters:
    update_rate: 100

    # 상태 브로드캐스터 로드
    joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster

    # 단일 관절 위치 제어기 로드 (6개)
    joint1_position_controller:
      type: forward_command_controller/ForwardCommandController
    joint2_position_controller:
      type: forward_command_controller/ForwardCommandController
    joint3_position_controller:
      type: forward_command_controller/ForwardCommandController
    joint4_position_controller:
      type: forward_command_controller/ForwardCommandController
    joint5_position_controller:
      type: forward_command_controller/ForwardCommandController
    joint6_position_controller:
      type: forward_command_controller/ForwardCommandController

# 각 컨트롤러 파라미터
joint1_position_controller:
  ros__parameters:
    joints:
      - Joint_1
    interface_name: position

joint2_position_controller:
  ros__parameters:
    joints:
      - Joint_2
    interface_name: position

joint3_position_controller:
  ros__parameters:
    joints:
      - Joint_3
    interface_name: position

joint4_position_controller:
  ros__parameters:
    joints:
      - Joint_4
    interface_name: position

joint5_position_controller:
  ros__parameters:
    joints:
      - Joint_5
    interface_name: position

joint6_position_controller:
  ros__parameters:
    joints:
      - Joint_6
    interface_name: position