parameter_manager:
  ros__parameters:
    joint_names: ["Joint_1","Joint_2","Joint_3","Joint_4","Joint_5","Joint_6"]
    joint_offsets: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    publish_topic: "/joint_states_calib"
    reseed_on_offset_change: true
    jump_threshold_deg: 7.0
